print("Calculo da gorjeta")
valor_total = float(input("Informe o total da compra: "))
gorjeta = float(input("Informe o valor que voce deseja dar de gorjeta, em porcentagem,: "))
total = valor_total * (gorjeta/100)
print(f"A sua compra foi de {valor_total}, a gorjeta é de {total:.2f} ")