print("Potenciação")
numero_base = float(input("Informe o numero que vai ser potenciado: "))
potencia = int(input("Informe o expoente que vai ser utilizado no seu numero: "))
potenciacao = (numero_base ** potencia)
print(f"O resultado da potencia é {potenciacao}")