nome = input("me diga seu nome por favor: ")
n = input("me diga qualquer numero ai sabixao")
tf = bool(input("Voce namora?"))
print (nome)
print (n)
print (tf)
print (type(nome))
print (type(n))
print (type(tf))